version: '3'

services:
  redis:
    image: redis

  web:
    image: staleflippant/primeservice:web
    command: sh -c "celery -A primeservice worker --loglevel=info & celery -A primeservice beat --loglevel=info & python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app-web
    ports:
      - "12345:8000"
    depends_on:
      - redis

  master:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    depends_on:
      - web
